export const ACTION_GET_CATEGORIES = "ACTION_GET_CATEGORIES";
export const ACTION_GET_CATEGORIES_SUC = "ACTION_GET_CATEGORIES_SUC";
export const ACTION_GET_CATEGORIES_FAL = "ACTION_GET_CATEGORIES_FAL";
