export const ACTION_GET_FEATURED_PLAYLISTS = "ACTION_GET_FEATURED_PLAYLISTS";
export const ACTION_GET_PLAYLISTS_BY_ID = "ACTION_GET_PLAYLISTS_BY_ID";
export const ACTION_GET_PLAYLISTS_SUC = "ACTION_GET_PLAYLISTS_SUC";
export const ACTION_GET_PLAYLISTS_FAL = "ACTION_GET_PLAYLISTS_FAL";

export const ACTION_SET_CURRENT_PLAYLISTID = "ACTION_SET_CURRENT_PLAYLISTID";
