export const ACTION_GET_TRACKS = "ACTION_GET_TRACKS";
export const ACTION_GET_TRACKS_SUC = "ACTION_GET_TRACKS_SUC";
export const ACTION_GET_TRACKS_FAL = "ACTION_GET_TRACKS_FAL";

export const ACTION_SET_PLAYING_ID = "ACTION_SET_PLAYING_ID";
